# Page settings

baseurl = "http://www.racebrocx.com/"
languageCode = "en-us"
title = "Race Brocx Resume"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-XXXXXXX-Y"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Hugo Responsive Resume/CV Theme for Developers"
    author = "Pavel Kanyshev"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # itâ€™s quick and easy to change the styling and colour scheme.

    styles = "styles.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Race Brocx"
        tagline = "Software Engineer"
        avatar = "profile.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: race.brocx@gmail.com"
        title = "race.brocx@gmail.com"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:+4253547981"
        title = "+4253547981"

        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "//racebrocx.com"
        title = "racebrocx.com"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/race-brocx-441b3564/"
        title = "linkedin.com/in/race-brocx-441b3564/"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/race-condition"
        title = "github.com/race-condition"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "BS in Computer Science"
        college = "University of Washington"
        dates = "2015"

    # Languages section
    [params.language]
        enable = false
        title = "Languages"

        [[params.language.list]]
        language = "English"
        level = "Native"

    # Interests section
    [params.interests]
        enable = false
        title = "Interests"

        [[params.interests.list]]
        interest = "Climbing"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "Over four years of professional development experience primarily focusing on Java."

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Software Engineer 1-2"
        dates = "2018 - Present"
        company = "Nordstrom"
        details = "Built microservices processing thousands of messages received through Kafka. Created REST API to serve data to services adding data to streaming messages. Built Incident Automator, which automates the processes involved in correlating incidents in the NOC (JavaScript, ServiceNow, Go)"

        [[params.jobs.list]]
        position = "Site Reliability Engineer"
        dates = "2017 - 2018"
        company = "Eagleview"
        details = "Modified existing software to correct errors, upgrade interfaces and improve performance (.NET Core, TFS, Jenkins)"

        [[params.jobs.list]]
        position = "Site Reliability Engineer"
        dates = "2015 - 2017"
        company = "Microsoft"
        details = "Implemented designs, including experimentation and multiple iterations for development projects utilizing .NET and TFS"

    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Projects"
        intro = ""

        [[params.projects.list]]
        title = "Enterprise Event Ledger Service"
        url = ""
        tagline = "REST API for accessing transaction data for Nordstrom"

        [[params.projects.list]]
        title = "Incident Automator"
        url = ""
        tagline = "Automates the tasks involved with responditing to high priority incidents for Nordstrom Operations Center"

        [[params.projects.list]]
        title = "Report Add on Generator"
        url = ""
        tagline = "Automates the process of generating add-ons and modifying Eagleview roof reports"

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "Java"
        level = "98%"

        [[params.skills.list]]
         skill = "C#"
         level = "95%"

        [[params.skills.list]]
        skill = "Go"
        level = "78%"

        [[params.skills.list]]
        skill = "Kafka"
        level = "55%"

        [[params.skills.list]]
        skill = "C++"
        level = "40%"

        [[params.skills.list]]
        skill = "Javascript"
        level = "35%"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = ""